# Generated by Django 5.2.14 on 2026-05-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default='/page/1/', max_length=50, verbose_name='Посилання сторінки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на зображення'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва категорії'),
        ),
    ]
